//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasePara
    {
        public string Company { get; set; }
        public Nullable<short> TwoDay { get; set; }
        public bool NoClockIn { get; set; }
        public bool NoClockOut { get; set; }
        public Nullable<short> LateTime { get; set; }
        public Nullable<short> LeaveTime { get; set; }
        public bool ISOverTime { get; set; }
        public Nullable<short> OverTime { get; set; }
        public Nullable<short> WorkDayLong { get; set; }
        public Nullable<float> WOverTime { get; set; }
        public Nullable<float> HOverTime { get; set; }
        public Nullable<float> FOverTime { get; set; }
        public bool IsAutoDownRec { get; set; }
        public string DownRecTime { get; set; }
        public Nullable<int> OvertimeIn { get; set; }
        public bool IsovertimeIn { get; set; }
        public bool DeductIn { get; set; }
        public bool DeductOut { get; set; }
    }
}
