//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatItem
    {
        public int Itemid { get; set; }
        public string ItemName { get; set; }
        public Nullable<short> Units { get; set; }
        public Nullable<float> MinUnit { get; set; }
        public Nullable<short> SRControl { get; set; }
        public bool IsAddup { get; set; }
        public bool IsTimes { get; set; }
        public string Showas { get; set; }
    }
}
