//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Record
    {
        public int Logid { get; set; }
        public string Userid { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public string CheckType { get; set; }
        public string Sensorid { get; set; }
        public Nullable<int> WorkType { get; set; }
        public Nullable<int> AttFlag { get; set; }
        public bool OpenDoorFlag { get; set; }
        public string Name { get; set; }
        public Nullable<int> Deptid { get; set; }
        public string Duty { get; set; }
        public string DeptName { get; set; }
        public string Clientid { get; set; }
        public string ClientName { get; set; }
        public string StatusText { get; set; }
    }
}
