//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public int Holidayid { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> BDate { get; set; }
        public Nullable<short> Days { get; set; }
    }
}
