//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPinfo
    {
        public int Opid { get; set; }
        public string Name { get; set; }
        public string Pwd { get; set; }
        public string Authority { get; set; }
        public string Deptpower { get; set; }
    }
}
